services:
  generative-style-transfer:
    build:
      context: app
      dockerfile: Dockerfile
    entrypoint:
      [
        "python3",
        "style_transfer.py",
        "-c=content.jpg",
        "-s=style.jpg",
        "--epochs=${EPOCHS}",
        "--steps_per_epoch=${STEPS_PER_EPOCH}",
        "--style_weight=${STYLE_WEIGHT}",
        "--content_weight=${CONTENT_WEIGHT}",
        "--total_variation_weight=${TOTAL_VARIATION_WEIGHT}",
        "--max_dim=${MAX_DIM}",
      ]
    volumes:
      - type: bind
        source: .
        target: /app/results/
      - type: bind
        source: ${CONTENT_PATH}
        target: /app/content.jpg
      - type: bind
        source: ${STYLE_PATH}
        target: /app/style.jpg
    image: style-transfer:latest
    runtime: nvidia
    tty: true
