services:
  generative-style-transfer:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        - CONTENT_PATH=${CONTENT_PATH}
        - STYLE_PATH=${STYLE_PATH}
        - EPOCHS=${EPOCHS}
        - STEPS_PER_EPOCH=${STEPS_PER_EPOCH}
        - STYLE_WEIGHT=${STYLE_WEIGHT}
        - CONTENT_WEIGHT=${CONTENT_WEIGHT}
        - TOTAL_VARIATION_WEIGHT=${TOTAL_VARIATION_WEIGHT}
        - MAX_DIM=${MAX_DIM}
        - USER=${USER}
    volumes:
      - type: bind
        source: .
        target: /home/${USER}/results/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: style-transfer:latest
    tty: true
