services:
  generative-style-transfer:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        - EPOCHS=${EPOCHS}
        - STEPS_PER_EPOCH=${STEPS_PER_EPOCH}
        - STYLE_WEIGHT=${STYLE_WEIGHT}
        - CONTENT_WEIGHT=${CONTENT_WEIGHT}
        - TOTAL_VARIATION_WEIGHT=${TOTAL_VARIATION_WEIGHT}
        - MAX_DIM=${MAX_DIM}
        - USER=${USER}
    volumes:
      - type: bind
        source: .
        target: /home/${USER}/results/
      - type: bind
        source: ${CONTENT_PATH}
        target: /home/${USER}/content.jpg
      - type: bind
        source: ${STYLE_PATH}
        target: /home/${USER}/style.jpg
      - type: bind
        source: ${MODEL_PATH}
        target: /home/${USER}/model_top.h5
      - type: bind
        source: ${HUB_MODULE}
        target: /home/${USER}/tf_hub_module
    ports:
      - "8888:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: style-transfer:latest
    tty: true
